# Generated by Django 5.0.2 on 2024-02-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='Имя (name)')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена (price)')),
                ('image', models.ImageField(upload_to='', verbose_name='Фоточки')),
                ('release_date', models.DateField(blank=True, default=None, verbose_name='Дата (release_date)')),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=55, unique=True, verbose_name='slug')),
            ],
        ),
    ]
